### ISSUE TITLE
"Zoom in intro" not working on new game in some cases.

### ISSUE THREAD

**Issue by 0x0ade** [AngelDE98/FEZMod#10]
Twitter conversation: https://twitter.com/Forstride/status/626315781219946496

Video describing the issue: https://www.youtube.com/watch?v=hFhH3B2pD5U

**Comment by AngelDE98** [comment]
Migrated to https://github.com/renaudbedard/fez-1.12-issues/issues/22, closing this issue here.

**Comment by 0x0ade** [comment]
Previously linked to wrong issue on https://github.com/renaudbedard/fez-1.12-issues. Correct issue is https://github.com/renaudbedard/fez-1.12-issues/issues/13. Anyone seeing this: Sorry for the spam.

Still needs confirmation if it's the same issue.

**Comment by renaudbedard** [comment]
FYI, I just fixed this in `fna-unstable` (hopefully!)
